#!/bin/bash
set -e

# 1. Save the name of the current branch
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

echo "Compiling SWE Resume..."
git checkout swe-profile
pdflatex resume.tex
mkdir -p builds # Force the folder to exist after the checkout
cp resume.pdf builds/Ray_Chua_SWE_Resume.pdf

echo "Compiling Quant Resume..."
git checkout quant-profile
pdflatex resume.tex
mkdir -p builds # Force the folder to exist after the checkout
cp resume.pdf builds/Ray_Chua_Quant_Resume.pdf

# 2. Clean up the auxiliary clutter generated by LaTeX
rm -f *.aux *.log *.out *.fls *.fdb_latexmk *.synctex.gz resume.pdf

# 3. Return to the original branch
git checkout $CURRENT_BRANCH

echo "========================================"
echo "Success! Your resumes are in the 'builds' folder."
